[package]
name = "AutoKeyboard"
version = "0.0.1"
authors = ["jiaqinglu"]
description = "Keyboard firmware written in Rust"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
rmk = { git = "https://github.com/haobogu/rmk.git", default-features = false, features = [
    "esp32s3_ble",
    "log",
    "storage",
    "vial"
] }
embassy-executor = { version = "0.10" }
esp-backtrace = { version = "0.19", features = [
    "esp32s3",
    "panic-handler",
    "println",
] }
esp-hal = { version = "1.1", features = ["esp32s3", "log-04",  "unstable"] }
esp-storage = { version = "0.9", features = ["esp32s3"] }
esp-alloc = { version = "0.10" }
esp-println = { version = "0.17", features = ["esp32s3", "log-04"] }
esp-radio = { version = "0.18", features = ["esp32s3", "unstable", "ble", "wifi"] }
esp-rtos = { version = "0.3.0", features = [
  "embassy",
  "esp-alloc",
  "esp-radio",
  "esp32s3",
  "log-04",
] }

trouble-host = { git = "https://github.com/haobogu/trouble", rev = "690373fd1166d16225b875435dd0600c92570e7d", features = [
    "gatt",
    "scan",
    "derive",
    "security",
    "serde",
]}

esp-bootloader-esp-idf = { version = "0.5", features = ["esp32s3", "log-04"] }
bt-hci = { version = "0.8" }
rand_core = { version = "0.6", default-features = false }
embassy-net = { version = "0.9.1", features = [
  "dhcpv4",
  "log",
  "medium-ethernet",
  "tcp",
  "udp",
] }
log = "0.4.27"
static_cell = "2.1.1"
rust-mqtt = { version = "0.5", default-features = false, features = ["log", "v5", "bump"] }
heapless = "0.9"

[build-dependencies]
xz2 = "0.1.7"
json = "0.12"
const-gen = "1.6"
embuild = "0.33"
cc = "1.2.9"

[[bin]]
name = "AutoKeyboard"
path = "src/main.rs"
test = false
bench = false

[profile.dev.package.esp-storage]
opt-level = 3

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'thin'
opt-level = 3
overflow-checks = false
